### ISSUE TITLE
openssl branch no decrpyting properly

### ISSUE THREAD

**Issue by samhodge** [dneprDroid/TFSecured#5]
Using a model that was AES encrypted using a previous version with patches to make the Python script work.

I am unable to use the OpenSSL branch to decrypt this model.

I posted on a closed ticket, but I think this really needs a ticket of its own

@dneprDroid 

I tried with your branch and things are indeed faster, 0.8s compared with 11s with O3 optimisation (on macOS 10.13 at least)

The problem is if I drop in identical code I get an error.

here is the code I am using

```
		cur_graph.last = graph_file_name;
		auto start = std::chrono::high_resolution_clock::now();
		std::cerr << "Start Decrypt" << std::endl;
		auto load_graph_status = tfsecured::GraphDefDecryptAES(graph_file_name,         // path to *.pb file (frozen graph)
			&graph_def,
			key);         // your key
		
		auto end = std::chrono::high_resolution_clock::now();
		std::cerr << "Start End decrypt" << std::endl;
		auto microseconds = std::chrono::duration_cast<std::chrono::microseconds>(end-start);
                 std::cerr << "Time Elapsed: " << microseconds.count() << " µs\n";
		if (!load_graph_status.ok()) {
			std::cerr << "What is the issue ? " << load_graph_status.error_message().c_str() << std::endl;
			return tensorflow::errors::NotFound("Failed to load compute graph at '", graph_file_name, "'");
		}
		else {
			graph_map[graph_file_name] = graph_def;
		}
```

and the output I get back

```
Start Decrypt
Start End decrypt
Time Elapsed: 879331 µs
What is the issue ? [OpenSSL] EVP_DecryptFinal_ex Error
```

So it looks like it is having issues with the alignment of bits being on a block boundary to do with padding, I will paste some related googling I did on the subject a few days ago.

If needed I can provide a .pb file and its key so you can reproduce the error at your end.

**Comment by samhodge** [comment]
Tried with OpenSSL 1.1.1a and 1.0.2r

Same result.

I will build a test for you.

**Comment by samhodge** [comment]
[deeplabv3_mnv2_dm05_pascal_trainaug_encrypted_frozen_inference_graph.pb.zip](https://github.com/dneprDroid/TFSecured/files/2986534/deeplabv3_mnv2_dm05_pascal_trainaug_encrypted_frozen_inference_graph.pb.zip)

Unencrypted model comes from http://download.tensorflow.org/models/deeplabv3_mnv2_dm05_pascal_trainaug_2018_10_01.tar.gz

Passphrase is "bigsecret" 


Let me know if you can decrypt this model on your end?

**Comment by samhodge** [comment]
OK here is the driver

```
#include <tensorflow/core/platform/init_main.h>
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/framework/tensor_shape.h>
#include "GraphDefDecryptor.hpp"

using namespace std;

int main(int argc, const char * argv[]) {
    //Popup numberwang;
    //numberwang.hotkeys();
    std::string fullpath=std::string("/Applications/Kognat/deeplabv3_mnv2_dm05_pascal_trainaug_encrypted_frozen_inference_graph.pb");
    tensorflow::GraphDef graph_def;
    
    
    std::string key("bigsecret");
    auto load_graph_status = tfsecured::GraphDefDecryptAES(fullpath,
                                                           &graph_def,
                                                           key);
    if (!load_graph_status.ok()){
        std::cerr << "That is no good: " <<load_graph_status.error_message().c_str() << std::endl;
        return -99;
    }
    return 0;
}
```

**Comment by samhodge** [comment]
Output is

```
That is no good: [OpenSSL] EVP_DecryptFinal_ex Error
Program ended with exit code: 157
```

**Comment by dneprDroid** [comment]
The error was caused by this line https://github.com/openssl/openssl/blob/1222d273d36277f56c3603a757240c386d55f318/crypto/evp/evp_enc.c#L531

because my python script and OpenSSL use different block sizes (32 and 16).

Check out the updated branch.

I re-encrypted your pb-model via updated script and it's working fine for me.

and also added additional error logging, `ERR_print_errors_fp(stderr)` is useful for reading error logs.

**Comment by samhodge** [comment]
Thanks, I will try it out tomorrow, it’s late on Saturday night in Adelaide

**Comment by samhodge** [comment]
Thanks @dneprDroid that fixes the issue, sorry I couldnt work it out myself.

Sunday got busy so I could only test now.
